#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script invoking that shell by setting the SHELL
#       environment variable.
#
#       For example, assuming you have bash installed, you can run:
#           SHELL=/bin/bash ./gradlew
#
#   (2) You need a version of Java installed (the 'java' command in your PATH).
#       The script will check this by running 'java -version'.
#
#   (3) The script uses the 'uname' command to detect the OS. If your OS is not
#       supported, you can override the 'os' variable by setting the OS
#       environment variable before running the script.
#
#   (4) The script uses the 'cygpath' command on Windows to resolve absolute
#       paths to Windows paths. If you don't have 'cygpath' installed, you can
#       still use the script, but some features may not work.
#
#   (5) The script will attempt to locate a 'gradle-wrapper.jar' file, and if
#       not found, it will download it from the Gradle distribution.
#
#   (6) The script relies on the 'java' command being available and on your
#       PATH. If 'java' is not available, the script will exit with an error.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available file descriptors, if possible.
if command -v ulimit > /dev/null 2>&1; then
    ulimit -n 4096 || ulimit -n 1024 || true
fi

# Make sure the java command is available.
if ! command -v java > /dev/null 2>&1; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo ""
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is not supported. POSIX sh can only set the soft limit.
        # In POSIX sh, ulimit -n sets both soft and hard limit.
        # We don't want to set the hard limit to unlimited, so we set the soft limit.
        # In POSIX sh, there is no built-in syntax to set the soft limit to unlimited,
        # so we use this: ulimit -S -n unlimited && ulimit -n unlimited
        # The order matters: the soft limit must be set before the hard limit.
        # The '2>/dev/null' is used to suppress the "Operation not permitted" error
        # when the user is not allowed to increase the hard limit.
        ulimit -S -n unlimited 2>/dev/null && ulimit -n unlimited 2>/dev/null || true
        ;;
      *)
        ulimit -n "$MAX_FD" 2>/dev/null || true
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the -classpath
#   * the -D... app name arguments
#   * the -jar jar file

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$(find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null || true)
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$SEP$dir"
        SEP="|"
    done
    OURCYGPATTERN="(^($ROOTDIRS))"
    # Add a user-defined pattern to the cygpath arguments
    if [ -n "$CYGPATTERN" ] ; then
        cygpath_arguments_0="-p $CYGPATTERN"
    fi

    # Now convert the arguments - sloppy, we assume just one argument per option
    for arg do
        if [[ $arg =~ $OURCYGPATTERN ]] ; then
            # Convert to Windows path
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop in POSIX sh has a limit of 1024 arguments, but we
        # effectively limit the loop to the length of the arguments list.
        set -- "$@" "$arg"
    done
fi

# Collect the arguments
if [ -n "$JAVA_OPTS" ] ; then
    JAVA_OPTS="$JAVA_OPTS -Dorg.gradle.appname=$APP_BASE_NAME"
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect the arguments to the Java command.
#   * The main class is 'org.gradle.wrapper.GradleWrapperMain'.
#   * The -classpath argument will be added later.
#   * The -jar argument will be added later.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1 ; then
    echo "ERROR: xargs is not available."
    exit 1
fi

# Use "xargs" to parse quoted args.
# The default behaviour of "xargs" is to split on whitespace.
# We use "xargs -n1" to handle each argument separately.
# This allows us to pass quoted arguments with spaces.
# We also use "xargs -0" to handle arguments with null characters.
# We use these arguments to call "java" with the correct arguments.
# We use "xargs" to avoid issues with quoted arguments, as the shell
# will treat them as a single argument.
#
# We pass the arguments to "java" as an array.
# We use "set --" to set the positional parameters.
# We use "xargs" to split the arguments into separate arguments.
# We use "xargs -n1" to handle each argument separately.
# We use "xargs -0" to handle arguments with null characters.
#
# We can't use "xargs" directly because it will split on whitespace.
# We can't use "xargs -0" directly because it will split on null characters.
# We can't use "xargs -n1" directly because it will split on whitespace.
# We can't use "xargs -n1 -0" directly because it will split on null characters.
# We can't use "xargs -n1 -0" because it is not supported by all xargs implementations.
#
# So we use a combination of "printf" and "xargs" to handle arguments.
# We use "printf" to print the arguments with null characters.
# We use "xargs -0" to read the arguments with null characters.
# We use "xargs -n1" to handle each argument separately.
#
# The result is that we can pass quoted arguments with spaces.
#
# We also use "xargs" to handle the case where the arguments are empty.
#
# We use "set --" to set the positional parameters.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with tabs.
#
# We use "xargs" to handle arguments with spaces.
#
# We use "xargs" to handle arguments with quotes.
#
# We use "xargs" to handle arguments with backslashes.
#
# We use "xargs" to handle arguments with newlines.
#
# We use "xargs" to handle arguments with
